#!/bin/bash
docker import chronicler-docker.tar \
  --change "WORKDIR chronicler" \
  --change "ENTRYPOINT [\"bash\", \"entrypoint.sh\"]" \
  --change "EXPOSE 1235" \
  lanseg/chronicler

#!/bin/bash
set -euo pipefail
docker run \
  --mount type=bind,source="`pwd`",target=/storage \
  -p 1235:1235 lanseg/chronicler \
  all /storage/config-docker.json
