#!/bin/sh
set -euo pipefail

if [[ "$( echo $@ | grep '\--config=' )"  == "" ]]
then
  echo "No config path configured"
  exit 1
fi

configPath="$( echo $@ | grep -o [^=]*$ )"

if [[ ! -f "$configPath" ]]
then
  echo "Config file at '$configPath' does not exist"
  exit 1
fi

telegramBotApiId="$( cat $configPath | grep telegramBotApiId | grep -o "[0-9]*" )"
telegramBotApiHash="$( cat $configPath | grep telegramBotApiHash | grep -o \":.*\" | grep -o "[0-9a-z]*" )"

echo "Config path: $configPath"
echo "Api id: $telegramBotApiId"
echo "Api hash: $telegramBotApiHash"

./telegram-bot-api --api-id=$telegramBotApiId --api-hash=$telegramBotApiHash  --dir=/tmp/telegram/files --temp-dir=/tmp/telegram/temp  --local -l log